<?php

include 'header.php';

$html = '<span>';
$html .= '<h1 id="title">upload nieuwe producten</h1>';
$html .= '<p>gegevens met * is vereist</p>';
$html .= '</span>';
echo $html;
//$html = '<button class="exitButton"><a href="home">X</a></button>';
$html = "<form method='POST' action='?op=create' style='padding-top: 50px; padding-bottom: 50px;'>";
$html .= "<input style='display: none;' name='op' placeholder='Naam:' value='create'>";
$html .= "<div class='product-addForm'>";
$html .= 	"<div>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Naam product</th></tr>";
$html .= 	       "<tr><td><input name='title' placeholder='Naam:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Platform (VR-brillen)</th></tr>";
$html .= 	       "<tr><td><input name='platform' placeholder='Platform:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Eigen display</th></tr>";
$html .= 	       "<tr><td><input name='eigenDisplay' placeholder='Eigen display:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Resolutie:</th></tr>";
$html .= 	       "<tr><td><input name='resulatie' placeholder='Resolutie:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Functies (VR-bril)</th></tr>";
$html .= 	       "<tr><td><input name='functies' placeholder='Functies (VR-bril):'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Aansluitingen VR-bril</th></tr>";
$html .= 	       "<tr><td><input name='aansluitingen' placeholder='Aansluitingen VR-bril:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Refresh rate</th></tr>";
$html .= 	       "<tr><td><input name='refreshRate' placeholder='Refresh rate:' ></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Prijs</th></tr>";
$html .= 	       "<tr><td><input name='prijs' placeholder='prijs:'></td></tr>";
$html .=	   "</table>";
$html .=    "</div>";

$html .= 	"<div>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Garantie</th></tr>";
$html .= 	       "<tr><td><input name='garantie' placeholder='Fabrieksgarantie:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Accu en accessories</th></tr>";
$html .= 	       "<tr><td><input name='accessoires' placeholder='Meegeleverde VR-bril accessoires:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie Product</th></tr>";
$html .= 	       "<tr><td><input name='infoProduct' placeholder='informatie Product:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie Merk</th></tr>";
$html .= 	       "<tr><td><input name='infoMerk' placeholder='Merk:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie Tweakers ID</th></tr>";
$html .= 	       "<tr><td><input name='infoTweakers' placeholder='Tweakers ID:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie EAN</th></tr>";
$html .= 	       "<tr><td><input name='infoEAN' placeholder='EAN:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie SKU</th></tr>";
$html .= 	       "<tr><td><input name='infoSKU' placeholder='SKU:'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Actie</th></tr>";
$html .= 	       "<tr><td style='padding: 0px;'>" . "<select id='actie-select' name='actie'><option value='0'>Nee</option><option value='1'>Ja</option></select>";
$html .=           "<input id='actie-korting' name='korting' placeholder='prijs:'>";
$html .=           "</td></tr>";
$html .=	   "</table>";
$html .=        '<div class="addform-buttons">';
$html .= 	      "<button type='submit' id='add-product'>Voeg product toe</button>";
$html .=        '</div>';
$html .=	"</div>";
$html .= "</div>";
$html .= "</form>";
//$html .= '<button class="exitButton" style="bottom: 3.6%;"><a href="home">X</a></button>';
echo $html;
include 'footer.php';

?>
