<?php

include 'header.php';

$html = '<span>';
$html .= '<h1 id="title">upload nieuwe producten</h1>';
$html .= '<p>gegevens met * is vereist</p>';
$html .= '</span>';
echo $html;
//$html = '<button class="exitButton"><a href="home">X</a></button>';
$html = "<form action='?op=create' style='padding-top: 50px; padding-bottom: 50px;'>";
$html .= "<input style='display: none;' name='op' placeholder='Naam:' value='create'>";
$html .= "<div class='product-addForm'>";
$html .= 	"<div>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Naam product</th></tr>";
$html .= 	       "<tr><td><input name='Naam' placeholder='Naam:' value='name'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Platform (VR-brillen)</th></tr>";
$html .= 	       "<tr><td><input name='Platform' placeholder='Platform:' value='Platform'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Eigen display</th></tr>";
$html .= 	       "<tr><td><input name='Display' placeholder='Eigen display:' value='display'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Resolutie:</th></tr>";
$html .= 	       "<tr><td><input name='Resolutie' placeholder='Resolutie:' value='Resolutie'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Functies (VR-bril)</th></tr>";
$html .= 	       "<tr><td><input name='Functies' placeholder='Functies (VR-bril):' value='Functies'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Aansluitingen VR-bril</th></tr>";
$html .= 	       "<tr><td><input name='Aansluitingen' placeholder='Aansluitingen VR-bril:' value='Aansluitingen'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Refresh rate</th></tr>";
$html .= 	       "<tr><td><input name='Refresh' placeholder='Refresh rate:' value='Platform'></td></tr>";
$html .=	   "</table>";
$html .=    "</div>";

$html .= 	"<div>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Garantie</th></tr>";
$html .= 	       "<tr><td><input name='' placeholder='Fabrieksgarantie:' value='Fabrieksgarantie'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Accu en accessories</th></tr>";
$html .= 	       "<tr><td><input name='Accessoires' placeholder='Meegeleverde VR-bril accessoires:' value='accessoires'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie Product</th></tr>";
$html .= 	       "<tr><td><input name='Info-product' placeholder='informatie Product:' value='infoProduct'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie Merk</th></tr>";
$html .= 	       "<tr><td><input name='Merk' placeholder='Merk:' value='Merk'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie Tweakers ID</th></tr>";
$html .= 	       "<tr><td><input name='Tweakers' placeholder='Tweakers ID:' value='Tweakers'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie EAN</th></tr>";
$html .= 	       "<tr><td><input name='EAN' placeholder='EAN:' value='EAN'></td></tr>";
$html .=	   "</table>";
$html .= 	   '<table class="detail-table">';
$html .=	       "<tr><th style='background: var(--grey);'>Extra informatie SKU</th></tr>";
$html .= 	       "<tr><td><input name='SKU' placeholder='SKU:' value='SKU'></td></tr>";
$html .=	   "</table>";
$html .=	"</div>";
$html .= "</div>";
$html .= '<div class="addform-buttons">';
$html .=    "<button id='add-product'>Voeg product toe</button>";
$html .= 	"<button type='submit' id='add-product'>Voeg product toe</button>";
$html .= '</div>';
$html .= "</form>";
//$html .= '<button class="exitButton" style="bottom: 3.6%;"><a href="home">X</a></button>';
echo $html;
include 'footer.php';

?>
